apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-harbor
provisioner: ceph.com/cephfs  # または rook-ceph.cephfs.csi.ceph.com
parameters:
  monitors: 192.168.11.201:6789,192.168.11.202:6789  # Proxmox の Ceph monitor IP
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: harbor
  claimRoot: /harbor-data
  fsName: cephfs
reclaimPolicy: Retain
