cephClusterSpec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  csi:
    enableRBD: true
    enableCephFS: true
    rbdPluginImage: quay.io/cephcsi/cephcsi:v3.9.0
    cephFSPluginImage: quay.io/cephcsi/cephcsi:v3.9.0

cephBlockPools: {}
cephFileSystems: {}
cephObjectStores: {}
