apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://operator.min.io/
    chart: tenant
    targetRevision: 7.0.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-tenant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
