apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.1
    helm:
      values: |
        expose:
          type: nodePort
          tls:
            enabled: true
            auto:
              commonName: 192.168.11.220
          nodePort:
            name: harbor
            ports:
              http:
                port: 80
              https:
                port: 443
        externalURL: https://192.168.11.220:30003
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
