apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-external-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AobaIwaki123/k8s-cluter
    targetRevision: main
    path: helm/rook/charts/rook-ceph-cluster
    helm:
      valuesObject:
        cephalusterSpec:
          external:
            enable: true
          crashCollector:
            disable: true
          healthCheck:
            daemonHealth:
              mon:
                disabled: false
                interval: 45s
        cephBlockPools: {}
        cephFileSystems: {}
        cephObjectStores: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph-external 
  