apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: external-cluster
  namespace: rook-ceph
spec:
  external:
    enable: true
  monitoring:
    enabled: true
    externalMgrEndpoints:
      - ip: "192.168.11.201"
      - ip: "192.168.11.202"
