apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gpu-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AobaIwaki123/k8s-cluster.git
    targetRevision: HEAD
    path: guide/6-llm-gpu-service/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
