externalURL: https://harbor.example.com

expose:
  type: nodePort
  tls:
    enabled: false  # ローカル検証の場合は false 推奨（HTTPS 無効）
  nodePort:
    name: harbor
    ports:
      http:
        port: 80
        nodePort: 30080
      https:
        port: 443
        nodePort: 30443


persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      existingClaim: ""
    chartmuseum:
      enabled: false
    jobservice:
      jobLog:
        existingClaim: ""
    database:
      existingClaim: ""
    redis:
      existingClaim: ""
    trivy:
      existingClaim: ""

  imageChartStorage:
    type: "gcs"
    gcs:
      bucket: "aobar"
      region: "asia-northeast1"
      keyfileSecret: "harbor-gcs-secret"
      keyfile: "key.json"
      encodedkey: ""  # ← これを明示的に無効化！

