apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls  # これが Harbor に渡す secret 名になります
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: harbor.shaoba.tech
  dnsNames:
    - harbor.shaoba.tech
