apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.strrl.dev
    chart: cloudflare-tunnel-ingress-controller
    targetRevision: 0.0.12
    helm:
      valuesObject:
        cloudflare:
          apiToken: oNoqkF5U0ac1rkzW6_iHdd-QP_JTAA3LsfrZdjSd
          accountId: b64715d4ccf3e955336bd290f574f6d4
          tunnelName: cf-tunnel-ingress-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
